In [1]:
import pandas as pd

In [4]:
mtr_lines_fares=pd.read_csv("../Data/MTR/mtr_lines_fares.csv")
mtr_lines_fares.head()

,id,SRC_STATION_NAME,SRC_STATION_ID,DEST_STATION_NAME,DEST_STATION_ID,OCT_ADT_FARE,OCT_STD_FARE,OCT_JOYYOU_SIXTY_FARE,SINGLE_ADT_FARE,OCT_CON_CHILD_FARE,OCT_CON_ELDERLY_FARE,OCT_CON_PWD_FARE,SINGLE_CON_CHILD_FARE,SINGLE_CON_ELDERLY_FARE
0,1,Central,1,Central,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,Central,1,Admiralty,2,4.9,3.2,2.0,5.0,3.2,2.0,2.0,3.5,3.5
2,3,Central,1,Tsim Sha Tsui,3,10.6,5.4,2.0,12.5,5.4,2.0,2.0,5.5,5.5
3,4,Central,1,Jordan,4,10.6,5.4,2.0,12.5,5.4,2.0,2.0,5.5,5.5
4,5,Central,1,Yau Ma Tei,5,13.2,6.5,2.0,15.5,6.5,2.0,2.0,6.5,6.5

In [5]:
MTR_DISTRICT=pd.read_excel("../Data/MTR/MTR_DISTRICT.xlsx")
MTR_DISTRICT.head()

  Line_Code  Station_ID DISTRICT Chinese_Name
0       ISL          37       東區           柴灣
1       ISL          36       東區          杏花邨
2       ISL          35       東區          筲箕灣
3       ISL          34       東區          西灣河
4       ISL          33       東區           太古

In [12]:
mtr_src_fares=mtr_lines_fares.merge(
    MTR_DISTRICT[['Station_ID','DISTRICT']],
    left_on=['SRC_STATION_ID'],
    right_on=['Station_ID']
    ,how='left')
mtr_dest_fares=mtr_src_fares.merge(
    MTR_DISTRICT[['Station_ID','DISTRICT']],
    left_on=['DEST_STATION_ID'],
    right_on=['Station_ID']
    ,how='left'
)
mtr_dest_fares=mtr_dest_fares.drop(columns=['Station_ID_x','Station_ID_y'])

In [ ]:
mtr_dest_fares.to_excel("../Data/MTR/MTR_Conversion.xlsx", engine='openpyxl')