In [1]:
import pandas as pd

In [2]:
Bus_FE_Processed=pd.read_excel("../Data/BUS/Bus_FE.xlsx",engine="openpyxl")
BUS_FE=pd.read_excel("../Data/BUS/Bus_FE.xlsx",engine="openpyxl")

In [3]:
Bus_FE_Processed_concat = pd.concat(
    [Bus_FE_Processed, BUS_FE[['ON_SEQ_STOP_ID', 'OFF_SEQ_STOP_ID']]],
    axis=1
)

In [4]:
Bus_FE_Processed_concat.to_excel("../Data/BUS/visualized_FE.xlsx",engine='openpyxl')

In [5]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(Bus_FE_Processed_concat, test_size=0.3, random_state=42)

In [6]:
test=pd.DataFrame(test)

In [7]:
visualized_outliers=pd.read_excel("../Data/BUS/visualized_outliers.xlsx",engine="openpyxl")

In [8]:
visualized_outliers.head()

,Unnamed: 0,PRICE,SPECIAL_TYPE,DISTANCE,JOURNEY_TIME,MEAN_COST_INDEX,Income(Median),Area,Population,Male Population,...,SERVICE_MODE_NT,SERVICE_MODE_R,SERVICE_MODE_T,residuals,residuals_lgb,residuals_rf,residuals_cat,residuals_rcv_stack,Lightgbm_Sigma_Outliers,Lightgbm_Box_Outliers
0,4145,6.4,1,3907,33,2.010127,16000,11.28,673166,312303,...,0,0,1,-0.917774,-0.869535,-0.957837,-0.953979,-0.917774,0,0
1,544,4.8,0,484,53,3.694651,20000,62.61,320094,146412,...,0,1,0,-0.961022,-0.490585,-1.061834,-1.095181,-0.961022,0,0
2,157,6.1,0,4558,52,1.978904,17000,39.40,263278,116239,...,0,1,0,-0.432855,-0.749305,-0.167449,-0.582478,-0.432855,0,0
3,274,7.4,0,2232,71,3.179194,16000,9.30,406802,187531,...,0,1,0,0.134815,0.096109,0.081511,0.186896,0.134815,0,0
4,538,8.8,0,3558,56,2.955857,16000,9.36,431090,197878,...,0,1,0,1.563700,1.651424,1.568735,1.438628,1.563700,0,0

In [9]:
test = test.reset_index(drop=True)
visualized_outliers = visualized_outliers.reset_index(drop=True)

# 再尝试拼接
test_concat = pd.concat(
    [test, visualized_outliers[['Lightgbm_Sigma_Outliers', 'Lightgbm_Box_Outliers']]],
    axis=1
)

In [10]:
print(test.index.equals(visualized_outliers.index))  # 应返回 True

True

In [11]:
print(test.shape)
print(visualized_outliers.shape)

(1354, 55)
(1354, 50)

In [12]:
test['Lightgbm_Sigma_Outliers'] = visualized_outliers['Lightgbm_Sigma_Outliers']
test['Lightgbm_Box_Outliers'] = visualized_outliers['Lightgbm_Box_Outliers']
print(test.shape)  # 输出应为 (1354, 50)

(1354, 57)

In [13]:
test[test['Lightgbm_Sigma_Outliers']==1]

,Unnamed: 0.1,Unnamed: 0,ROUTE_ID,ROUTE_SEQ,ON_SEQ,OFF_SEQ,PRICE,ROUTE_NAMES,COMPANY_CODE,SERVICE_MODE,...,Male Population,Female Population,Gender Ratio,Population Density,Num_Bus_Stop,Bus Stop Density,ON_SEQ_STOP_ID,OFF_SEQ_STOP_ID,Lightgbm_Sigma_Outliers,Lightgbm_Box_Outliers
9,3928,641659,1000239,2,5,20,9.6,61P,KMB,T,...,240321,266558,902,5786.289954,238,2.716895,13103,10000109,1,1
13,1128,136704,1357,1,1,12,9.8,85X,KMB,R,...,317927,374879,848,10001.530244,281,4.056590,6175,884,1,1
18,429,50312,1158,2,17,20,9.6,296C,KMB,R,...,187531,219271,855,43742.150538,152,16.344086,4081,823,1,1
53,2216,338724,1787,1,16,17,8.2,93,CTB,T,...,116239,147039,791,6682.182741,279,7.081218,345,346,1,1
63,438,52487,1163,1,5,8,9.8,299X,KMB,R,...,317927,374879,848,10001.530244,281,4.056590,6113,6119,1,1
120,2550,395964,8178,1,9,16,9.3,46P,KMB,T,...,232213,263585,881,21242.416452,221,9.468723,9595,13245,1,1
146,3388,546572,8613,1,1,6,9.6,59M,KMB,T,...,240321,266558,902,5786.289954,238,2.716895,12530,13081,1,1
186,2194,336720,1777,1,9,10,8.7,720A,CTB,NT,...,67075,99620,673,15666.823308,207,19.454887,18,19,1,1
200,3864,629983,1000200,1,19,36,9.5,N78,KMB,NT,...,145343,164288,885,2268.192806,236,1.728811,6507,12393,1,1
204,2876,450444,8382,1,10,26,6.7,47X,KMB,T,...,232213,263585,881,21242.416452,221,9.468723,9595,9511,1,1
243,3458,557074,8654,1,5,7,8.7,720P,CTB,T,...,98282,137671,714,18801.035857,234,18.645418,21,8008,1,1
326,3160,500743,8556,2,2,32,7.4,32H,KMB,R,...,232213,263585,881,21242.416452,221,9.468723,9558,1180,1,1
355,4447,719224,1000537,1,23,28,7.4,272P,KMB,T,...,232213,263585,881,21242.416452,221,9.468723,9566,9498,1,1
361,1730,239267,1613,2,6,8,8.7,788,CTB,R,...,67075,99620,673,15666.823308,207,19.454887,30,32,1,1
367,196,25763,1057,2,1,12,9.3,208,KMB,R,...,138873,171774,808,44441.630901,210,30.042918,1284,4234,1,1
374,2053,314621,1736,1,1,33,9.6,N1,NLB,NT,...,84985,100297,847,1009.656150,259,1.411367,12000,11075,1,1
415,239,28502,1078,1,1,3,9.3,238P,KMB,T,...,146412,173682,843,5112.505989,183,2.922856,9664,9662,1,1
434,1497,210218,1526,2,11,17,9.4,260,CTB,R,...,116239,147039,791,6682.182741,279,7.081218,411,417,1,1
448,718,81163,1234,1,1,4,9.3,48X,KMB,R,...,317927,374879,848,10001.530244,281,4.056590,6136,985,1,1
494,2316,363445,1897,1,10,11,7.7,930A,CTB,T,...,67075,99620,673,15666.823308,207,19.454887,31,10000110,1,1
509,4125,670086,1000314,2,17,20,9.8,96,KMB,T,...,146038,170432,857,2135.569202,259,1.747756,13180,10000017,1,1
544,2605,407513,8222,1,19,23,7.4,240X,KMB,T,...,232213,263585,881,21242.416452,221,9.468723,9566,10000162,1,1
551,2302,359655,1890,2,3,6,8.8,30X,CTB,R,...,98282,137671,714,18801.035857,234,18.645418,23,3185,1,1
596,2213,339279,1786,1,14,15,8.2,93,CTB,T,...,116239,147039,791,6682.182741,279,7.081218,345,346,1,1
648,426,50270,1158,2,9,11,9.6,296C,KMB,R,...,138873,171774,808,44441.630901,210,30.042918,4104,9111,1,1
664,2572,400302,8196,2,14,18,9.4,88X,KMB,T,...,312303,360863,865,59677.836879,291,25.797872,706,13228,1,1
712,2348,369048,8009,1,9,20,9.3,203S,KMB,T,...,138873,171774,808,44441.630901,210,30.042918,4015,12746,1,1
720,1720,237388,1611,2,1,6,8.7,780,CTB,R,...,98282,137671,714,18801.035857,234,18.645418,240,13071,1,1
737,1476,207229,1520,2,1,16,9.4,23,CTB,R,...,98282,137671,714,18801.035857,234,18.645418,330,10000285,1,1
741,3811,624646,1000091,1,3,6,9.9,NR61,CTB,T,...,312303,360863,865,59677.836879,291,25.797872,1151,1325,1,1
752,1718,237262,1611,1,1,12,8.7,780,CTB,R,...,233542,296061,789,29211.417540,222,12.244898,917,13,1,1
850,2685,419814,8264,1,2,10,9.0,36X,KMB,T,...,232213,263585,881,21242.416452,221,9.468723,9591,9534,1,1
911,354,42612,1125,1,23,28,7.4,272P,KMB,T,...,232213,263585,881,21242.416452,221,9.468723,9566,9498,1,1
974,3926,641515,1000239,1,1,14,9.6,61P,KMB,T,...,240321,266558,902,5786.289954,238,2.716895,13319,13334,1,1
985,4112,666481,1000307,1,1,8,9.4,42,CTB,T,...,116239,147039,791,6682.182741,279,7.081218,491,315,1,1
1047,1869,263618,1670,2,24,27,8.8,99,CTB,R,...,233542,296061,789,29211.417540,222,12.244898,112,657,1,1
1050,3929,641577,1000239,2,1,4,9.6,61P,KMB,T,...,146412,173682,843,5112.505989,183,2.922856,9629,12451,1,1
1071,2303,359630,1890,2,1,6,9.4,30X,CTB,R,...,98282,137671,714,18801.035857,234,18.645418,468,3185,1,1
1080,2552,395991,8179,1,1,7,9.7,99X,CTB,T,...,116239,147039,791,6682.182741,279,7.081218,12924,313,1,1
1110,4072,661131,1000286,2,1,11,9.2,97,KMB,T,...,223094,265943,839,3586.629996,239,1.752842,1046,10000019,1,1
1139,1714,237846,1609,2,24,27,8.8,77,CTB,R,...,233542,296061,789,29211.417540,222,12.244898,112,63,1,1
1154,358,43542,1126,2,1,6,8.6,272S,KMB,T,...,317927,374879,848,10001.530244,281,4.056590,12408,884,1,1
1155,3536,569335,8708,1,1,8,9.3,47X,KMB,T,...,317927,374879,848,10001.530244,281,4.056590,6047,852,1,1
1185,1485,734515,1522,1,18,36,9.4,25,CTB,R,...,233542,296061,789,29211.417540,222,12.244898,3067,63,1,1
1237,1971,293918,1707,1,10,19,9.7,N8P,CTB,N,...,67075,99620,673,15666.823308,207,19.454887,3021,297,1,1
1250,4399,712416,1000500,1,17,21,9.7,582,CTB,R,...,146038,170432,857,2135.569202,259,1.747756,10000288,6179,1,1
1281,2157,331452,1763,2,1,13,9.6,41A,CTB,R,...,233542,296061,789,29211.417540,222,12.244898,179,3217,1,1
1282,1729,239209,1613,2,1,5,8.7,788,CTB,R,...,98282,137671,714,18801.035857,234,18.645418,125,647,1,1
1322,1814,249778,1647,1,1,15,9.4,93A,CTB,T,...,116239,147039,791,6682.182741,279,7.081218,659,346,1,1
1343,4102,666027,1000304,1,1,14,9.4,38,CTB,R,...,116239,147039,791,6682.182741,279,7.081218,10000142,315,1,1

In [14]:
test.to_excel("../Data/BUS/visualized_FE_test.xlsx",engine='openpyxl')